config/routes.rb
Rails.application.routes.draw do
  get 'hyper_link/show'
  devise_for :users

  resources :users, only: [] do
    resources :notes do
      collection do
        get 'search', action: :search, as: :search
      end
    end
  end

  get 'hyperlink/:id', action: :show, controller: 'hyper_links', as: :hyperlink

  resources :collaborators, only: %i(index update) do
    collection do
      get 'collaboration_info/:user_id/hyperlink/:hyper_link_id', action: :get_collaboration_information, as: :collab_info
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :user
  belongs_to :hyper_link

  scope :most_recent_collaborators, -> (hyper_link_id) {where(hyper_link_id: hyper_link_id).where('collaborators.updated_at > ?', Time.now - 2.minutes)}
end

app/models/hyper_link.rb
class HyperLink < ApplicationRecord
  belongs_to :note
  enum mode: [:view, :edit]
  has_many :collaborators
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  has_many :hyper_links

  after_create_commit :create_hyper_links


  private

  def create_hyper_links
    begin
      retries ||= 0
      ActiveRecord::Base.transaction do
        self.hyper_links << HyperLink.create(note_id: self.id, uuid: SecureRandom.uuid, mode: 'view')
        self.hyper_links << HyperLink.create(note_id: self.id, uuid: SecureRandom.uuid, mode: 'edit')
      end
    rescue
      retry if (retries += 1) < 3
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notes
  has_many :collaborators
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!


  def after_sign_in_path_for(resource)
    stored_location_for(resource) || user_notes_url(resource)
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def index
    collaborators = Collaborator.joins(:user)
                        .most_recent_collaborators(params[:hyper_link_id])
                        .pluck('users.email')
    render json: {collaborators: collaborators}, status: :ok
  end

  def get_collaboration_information
    collaborator = Collaborator.find_by(user_id: params[:user_id], hyper_link_id: params[:hyper_link_id])
    collaborator = Collaborator.create(user_id: params[:user_id], hyper_link_id: params[:hyper_link_id]) if collaborator.nil?
    render json: collaborator, only: [:id], status: :ok
  end

  def update
    collaborator = Collaborator.find(params[:id])
    collaborator.updated_at = Time.now
    if collaborator.save
      render json: collaborator, status: :ok
    else
      render status: :unprocessable_entity
    end
  end
end

app/controllers/hyper_links_controller.rb
class HyperLinksController < ApplicationController
  def show
    @hyperlink = HyperLink.includes(:note).where(uuid: params[:id]).first
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:edit, :update, :destroy]

  def index
    @notes = current_user.notes
  end

  def show
    @note = Note.includes(:hyper_links).where(id: params[:id]).first
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @note, only: [:title, :body]}
    end
  end

  def new
    @note = Note.new
  end

  def edit
  end

  def create
    @note = Note.new(note_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @note.save
        format.html { redirect_to user_note_url(current_user, @note), notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to user_note_path(current_user, @note), notice: 'Note was successfully updated.' }
        format.json { render json: @note, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to user_notes_url(current_user), notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @notes = current_user.notes.where("title LIKE ?", "%#{params[:term]}%")
    respond_to do |format|
      format.js
    end
  end

  private
    def set_note
      @note = Note.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/hyper_link_helper.rb
module HyperLinkHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/hyper_links/_collaboration_handler.html.erb
<script type = "text/javascript" charset = "utf-8" >
    $(document).ready(function(){
        function start_update_collaboration(collaboration_id) {
            var url = '<%= collaborator_url(0) %>';
            url = url.replace('/0', '/' + collaboration_id);
            setInterval(function(){
                $.ajax({
                    type: "PATCH",
                    url: url,
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function(data){},
                    failure: function(errMsg) {
                        alert(errMsg);
                    }
                });
            }, 5000);
        }

        function start_update_collaborators(collaboration_id) {
            var url = '<%= collaborators_url %>';
            setInterval(function(){
                $.ajax({
                    type: "GET",
                    url: url,
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    data: {
                        "hyper_link_id": '<%= hyperlink.id %>'
                    },
                    success: function(data){
                        $("#collabs").text(data["collaborators"].join(','))
                    },
                    failure: function(errMsg) {
                        alert(errMsg);
                    }
                });
            }, 5000);
        }

        $.ajax({
            type: "GET",
            url: '<%= collab_info_collaborators_url(current_user.id, hyperlink.id) %>',
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function(data){
                start_update_collaboration(data["id"]);
                start_update_collaborators(data["id"]);
            },
            failure: function(errMsg) {
                alert(errMsg);
            }
        });
    });

</script>

app/views/hyper_links/_edit_mode.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <p id="note_title"><%= hyperlink.note.title %></p>
</p>

<p>
  <strong>Body:</strong>
  <p id="note_body"><%= hyperlink.note.body %></p>
</p>

------------------------------------------------------------------
</hr>

<h1>Editing Note Hyperlink</h1>

<%= render 'form', note: hyperlink.note, url:user_note_path(current_user, hyperlink.note) %>


---------------------------------------------------------------------
</hr>
<h1>Most recently collaborators</h1>
<p id="collabs"></p>

<%= link_to 'Back', user_notes_path(current_user) %>

<%= render 'hyper_links/collaboration_handler', hyperlink: hyperlink%>
<%= render 'hyper_links/load_note_body_script', hyperlink: hyperlink, url:  user_note_url(current_user, hyperlink.note.id)%>
<%= render 'hyper_links/sync_input_fields_with_view_script', hyperlink: hyperlink, url:  user_note_url(current_user, hyperlink.note.id)%>

app/views/hyper_links/_form.html.erb
<%= form_with(model: note, local: true, url: url) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: 'title_input' %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: 'body_input' %>
  </div>

<% end %>

app/views/hyper_links/_load_note_body_script.html.erb
<script type = "text/javascript" charset = "utf-8" >
  $(document).ready(function(){
      function update_input_fields() {
          if($("#title_input").length){
              $("#title_input").val($("#note_title").text());
          }
          if($("#body_input").length){
              $("#body_input").val($("#note_body").text());
          }
      };

      setInterval(function(){
          $.ajax({
              type: "GET",
              url: '<%= url %>',
              contentType: "application/json; charset=utf-8",
              dataType: "json",
              success: function(data){
                  $("#note_title").text(data['title']);
                  $("#note_body").text(data['body']);
                  update_input_fields();
              },
              failure: function(errMsg) {
                  alert(errMsg);
              }
          });
      }, 5000);
  });
</script>

app/views/hyper_links/_sync_input_fields_with_view_script.html.erb
<script type = "text/javascript" charset = "utf-8" >
    $(document).ready(function(){
        var typingTimer;
        var doneTypingInterval = 3000;
        var $title_input = $('#title_input');
        var $body_input = $('#body_input');

        $title_input.on('keyup', function () {
            clearTimeout(typingTimer);
            typingTimer = setTimeout(update_note, doneTypingInterval);
        });

        $body_input.on('keyup', function () {
            clearTimeout(typingTimer);
            typingTimer = setTimeout(update_note, doneTypingInterval);
        });

        $title_input.on('keydown', function () {
            clearTimeout(typingTimer);
        });

        $body_input.on('keydown', function () {
            clearTimeout(typingTimer);
        });

        function update_note() {
            var input = {title: $("#note_title").text(), body: $("#note_body").text()};
            $.ajax({
                type: "PATCH",
                url: '<%= url %>',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                data: JSON.stringify({ note: input }),
                success: function(data){},
                failure: function(errMsg) {
                    alert(errMsg);
                }
            });
        }

        $("#title_input").on("input", function() {
            $("#note_title").text($(this).val());
        });

        $("#body_input").on("input", function() {
            $("#note_body").text($(this).val());
        });
    });
</script>

app/views/hyper_links/_view_mode.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <p id="note_title"><%= hyperlink.note.title %></p>
</p>

<p>
  <strong>Body:</strong>
  <p id="note_body"><%= hyperlink.note.body %></p>
</p>

---------------------------------------------------------------------
</hr>
<h1>Most recently collaborators</h1>
<p id="collabs"></p>

<%= link_to 'Back', user_notes_path(current_user) %>

<%= render 'hyper_links/collaboration_handler', hyperlink: hyperlink%>
<%= render 'hyper_links/load_note_body_script', hyperlink: hyperlink, url:  user_note_url(current_user, hyperlink.note.id)%>

app/views/hyper_links/show.html.erb
<% if @hyperlink.view? %>
  <%= render 'view_mode', hyperlink: @hyperlink %>
<% else %>
  <%= render 'edit_mode', hyperlink: @hyperlink %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NotesApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note, local: true, url: url) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/_list_notes.html.erb
<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
    <% notes.each do |note| %>
      <tr>
        <td><%= note.title %></td>
        <td><%= note.body %></td>
        <td><%= link_to 'Show', user_note_path(current_user, note) %></td>
        <td><%= link_to 'Edit', edit_user_note_path(current_user, note) %></td>
        <td><%= link_to 'Destroy', user_note_path(current_user, note), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/notes/_search_action.html.erb
<script type = "text/javascript" charset = "utf-8" >
    $(document).ready(function(){

        $("#src-btn").click(function(){
            console.log($("#search-note").val())
            $.ajax({
                type: "GET",
                url: '<%= url %>',
                contentType: "application/json; charset=utf-8",
                dataType: "script",
                data: {
                    term: $("#search-note").val()
                },
                success: function(data){
                },
                failure: function(errMsg) {
                    alert(errMsg);
                }
            });
        })
    });
</script>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note, url: user_note_path(current_user, @note) %>

<%= link_to 'Show', user_note_path(current_user, @note) %> |
<%= link_to 'Back', user_note_path(current_user, @note) %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notes</h1>
search: <input type="text" id="search-note"> <input type="button" value="search" id="src-btn">

<div id="notes-searchable">
  <%= render 'list_notes', notes: @notes %>
</div>

<br>

<%= link_to 'New Note', new_user_note_path(current_user) %>
<%= render 'search_action', url: search_user_notes_url(current_user.id)  %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note, url: user_notes_path(current_user, @note) %>

<%= link_to 'Back', user_notes_path %>

app/views/notes/search.js.erb
$('div#notes-searchable').html("<%= escape_javascript(render :partial => 'list_notes', :locals=> { notes: @notes } ) %>")

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @note.body %>
</p>

<p>
  <strong>hyperlinks:</strong>
  </br>
  <% @note.hyper_links.each do |hyper_link| %>
    <strong><%= hyper_link.mode %> link</strong>:
    <%= link_to 'visit', hyperlink_url(hyper_link.uuid) %> (<%= hyperlink_url(hyper_link.uuid) %>)
    </br>
  <% end %>
</p>

<%= link_to 'Edit', edit_user_note_path(current_user, @note) %> |
<%= link_to 'Back', user_notes_path(current_user) %>